Add explicit "--migrate" option, no longer pass "--migrate" option to gcloud (#531)
Adds an explicit "--migrate" commandline option (which defaults to false) to minimize risk of
accidentally redirectin traffic to a broken version.

Also remove passing of "--migrate" to gcloud, since that does not seem
to support it at all, since it prints an error message:

    $ gcloud --verbosity=debug --project dartlang-pub app services set-traffic default --splits 20171107t112042=1 --migrate  -q
    ...
    Setting the following traffic allocations:
     - dartlang-pub/default/20171107t112042: 1.0
    Any other versions on the specified services will receive zero traffic.
    ...

    INVALID_ARGUMENT: Invalid request.
    - '@type': type.googleapis.com/google.rpc.BadRequest
      fieldViolations:
      - description: Traffic migration does not support Managed VMs.
	field: service
      - description: Traffic migration does not support Managed VMs.
	field: service
      - description: Warmup requests must be enabled for all versions that will gain additional
	  traffic as a result of the traffic migration.
	field: service.split.allocations[20171107t112042]
    TrafficSplitError: Issue setting traffic on service(s): default
    ...

Also reduce code duplication in the deploy script.