Fix a number of 'Internal server error's
This ensures that 'appHandler' always return Future<shelf.Response>. This
is expected by the caller which has a .catchError on the return value.

The following messages where logged to stderr by the application:

bin/server.dart 96:64  main.<fn>.<async>.<fn>.<async>.<fn>.<async>.<fn>.<fn>.<fn>.<async>
Error thrown by handler.
dart:core              Object.noSuchMethod
Arguments: [Closure: (dynamic, dynamic) => dynamic]
Receiver: Instance of 'Response'
NoSuchMethodError: method not found: 'catchError'

Class 'Response' has no instance method 'catchError'.
ERROR - 2015-04-20 12:45:29.067

Prepare version for new release

R=wibling@google.com

BUG=https://github.com/dart-lang/pub-dartlang-dart/issues/4
BUG=https://github.com/dart-lang/pub-dartlang-dart/issues/5

Review URL: https://codereview.chromium.org/1094123002